name: ASP.NET MVC (.NET Framework 4.8) to App Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: aspnet-mvc-dotnetframework48
    steps:
      - uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        
      - name: Restore NuGet packages
        run: nuget restore AspnetMvc48.sln
      
      - name: Build
        run: msbuild AspnetMvc48.sln
